version: '3.4'

services:
  microservices.web:
    image: ${DOCKER_REGISTRY-}microservicesweb
    environment:
        - RepoUrl=http://microservices.repo/people/employees/20
        - SalaryUrl=http://microservices.salary/salary/calculate
        - ASPNETCORE_URLS=http://+:5000
    build:
      context: .
      dockerfile: Microservices.Web/Dockerfile
    ports:
        - 5000:80

  microservices.repo:
    image: ${DOCKER_REGISTRY-}microservicesrepo
    build:
      context: .
      dockerfile: Microservices.Repo/Dockerfile

  microservices.salary:
    image: ${DOCKER_REGISTRY-}microservicessalary
    build:
      context: .
      dockerfile: Microservices.Salary/Dockerfile      